framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'

            async:
                dsn: 'doctrine://default'
                options:
                    auto_setup: 0
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    delay: 1000
                    max_delay: 86400
                    max_retries: 3
                    multiplier: 3

            failed:
                dsn: 'doctrine://default'
                options:
                    queue_name: failed
                retry_strategy:
                    delay: 1000
                    max_delay: 86400
                    max_retries: 10
                    multiplier: 3

        default_bus: command.bus

        buses:
            command.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                    allow_no_senders: true
                middleware:
                - validation
                - doctrine_transaction

            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true
                middleware:
                - validation

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
