networks:
  default:
    name: 'app'
    driver: 'bridge'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: '${APP_DOCKER_CONTAINER_PREFIX}-db'
    image: 'mysql:8.0-debian'
    restart: 'unless-stopped'
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  ###< doctrine/doctrine-bundle ###

  php-fpm:
    container_name: '${APP_DOCKER_CONTAINER_PREFIX}-php-fpm'
    restart: 'unless-stopped'
    cpus: 4
    mem_limit: 8G
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
    build:
      context: '.'
      dockerfile: './docker/php-fpm/Dockerfile'
      args:
        PUID: ${PUID}
        PGID: ${PGID}
#    volumes:
#    - '.:/var/www:rw'

  nginx:
    container_name: '${APP_DOCKER_CONTAINER_PREFIX}-nginx'
    restart: 'unless-stopped'
    cpus: 4
    mem_limit: 8G
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
    build:
      context: '.'
      dockerfile: './docker/nginx/Dockerfile'
      args:
        APP_PHP_FPM_CONTAINER_NAME: '${APP_DOCKER_CONTAINER_PREFIX}-php-fpm'
        PHP_UPSTREAM_PORT: '9000'
    ports:
    - '${APP_NGINX_HOST_HTTP_PORT}:80'
    - '${APP_NGINX_HOST_HTTPS_PORT}:443'
    depends_on:
    - 'php-fpm'
#    volumes:
#    - '.:/var/www:rw'
