#
# Slash "/" at the end of dirs is needed
#
imports:
# (PRIORITY LOW)
-   resource: 'service_hierarchy/services_rest.yaml'
-   resource: 'service_hierarchy/parameters/'
-   resource: 'service_hierarchy/services/'
-   resource: 'service_hierarchy/client/'
# (PRIORITY HIGH)

# when always OVERRIDES
when@test:
    imports:
    # priority (low)
    -   resource: 'service_hierarchy/test/parameters/'
    -   resource: 'service_hierarchy/test/services/'
    # priority (high)
